### ISSUE TITLE
Undefined subroutine &main::authentic called at /usr/local/webmin/authentic-theme/index.cgi line 12.

### ISSUE THREAD

**Issue by lionslair** [webmin/authentic-theme#1634] opened 2022-11-27 23:04 UTC
I am getting the following error having just updated to webmin 2.003

```
Error — Perl execution failed

Undefined subroutine &main::authentic called at /usr/local/webmin/authentic-theme/index.cgi line 12.

```

**Comment by pbobbenb** [comment] 2022-11-30 13:33
Also getting the same error with updating to Webmin 2.010 on macOS 10.14.6.

**Comment by iliajie** [comment] 2022-11-30 13:57
> I am getting the following error having just updated to webmin 2.003

Could you provide more details about your system? Did you try restarting Webmin manually?

**Comment by lionslair** [comment] 2022-11-30 22:52
Yes I have. Mis of Ubuntu 20.04 22.04 servers plug popos 22.04 desktop. All same issue on update. Only way to resolve is to run the webmin update-from-repo.sh script.

Reboot / restart etc did not fix it. 

I checked against the files on git and they are matching

**Comment by iliajie** [comment] 2022-11-30 23:14
So, update wasn't installed package manager (Deb)?

**Comment by lionslair** [comment] 2022-11-30 23:20
No I have always used the .tar.gz version. Both install and update. Doesn't the download. Does the install then when it refreshes get the error message above

**Comment by swelljoe** [comment] 2022-11-30 23:50
> No I have always used the .tar.gz version. 

That's a mistake. If you have a good package manager (Ubuntu does), you should use it.

**Comment by iliajie** [comment] 2022-12-01 00:30
Got it. I can reproduce the problem when updating from the source, as `vendor_perl` not getting included.

**Comment by iliajie** [comment] 2022-12-01 01:16
But the solution for the problem on my end was manually restart Webmin to re-read files from a new directory.

@jcameron Jamie, is there anything we can do about it for `.tar.gz` releases?

**Comment by iliajie** [comment] 2022-12-01 01:33
Jamie, after you install Webmin 2.010 over 2.000 (in `.tar.gz` mode) `systemd` doesn't load a new `ExecStart=/root/webmin-2.010/miniserv.pl` (from a new directory) until you run `systemctl restart webmin` manually.

> Reboot / restart etc did not fix it.

I don't see how this is possible.

**Comment by lionslair** [comment] 2022-12-01 03:02
> Jamie, after you install Webmin 2.010 over 2.000 (in `.tar.gz` mode) `systemd` doesn't load a new `ExecStart=/root/webmin-2.010/miniserv.pl` (from a new directory) until you run `systemctl restart webmin` manually.
> 
> > Reboot / restart etc did not fix it.
> 
> I don't see how this is possible.

Mine seems to have the update maintained in /usr/local/webmin  Not a folder suffixed with the version like it used to be

**Comment by pbobbenb** [comment] 2022-12-06 22:14
Managed to partly fix my problem by applying this fix: https://github.com/webmin/webmin/pull/1807/commits/a9349c7fe5e18d32672423ffa310384bb8f0fc5a

But since my perllib path is empty in the config I had to change PERLLIB to LIBROOT in authentic-lib.pl for it to work.

Question is, should I set the perllib path or not?
Reading through some commits and issues here on Github I am a bit confused to whether if it should be set or not.

**Comment by pbobbenb** [comment] 2022-12-06 22:25
I'm running on macOS 10.14.6 so RPM or DEB will be difficult ;-)

**Comment by iliajie** [comment] 2022-12-06 22:27
Does everything work for you as expected?

**Comment by pbobbenb** [comment] 2022-12-06 22:32
Seems so, only Filemanager does not work, but I usually never use it.
Error is: Undefined subroutine &filemin::mimetype called at ./filemin-lib.pl line 466.

**Comment by iliajie** [comment] 2022-12-06 22:41
Have you restarted Webmin after applying the patch you mentioned? What theme do you use?

**Comment by pbobbenb** [comment] 2022-12-06 22:46
Yes I have restarted Webmin, theme is Authentic v20.10.

**Comment by pbobbenb** [comment] 2022-12-06 22:55
Oops, my bad, managed to make LIBROOT as LIBROOT_ROOT in WebminCore.pm, fixed that but then I got these errors instead:

[06/Dec/2022:23:51:39 +0100] [192.168.x.x] /extensions/file-manager/fetcher.cgi : Perl execution failed : Undefined subroutine &extensions::is_root called at /usr/local/webmin/authentic-theme/extensions/file-manager/fetcher.cgi line 14.

[06/Dec/2022:23:51:40 +0100] [192.168.x.x] /extensions/file-manager/tree.cgi : Perl execution failed : Undefined subroutine &extensions::kill_previous called at /usr/local/webmin/authentic-theme/extensions/file-manager/tree.cgi line 14.

[06/Dec/2022:23:51:40 +0100] [192.168.x.x] /extensions/file-manager/list.cgi : Perl execution failed : Undefined subroutine &extensions::print_content called at /usr/local/webmin/authentic-theme/extensions/file-manager/list.cgi line 12.

**Comment by pbobbenb** [comment] 2022-12-06 23:00
Ah, I see there is a PERLLIB in authentic-theme/extensions/file-manager/file-manager-lib.pl, which won't work since my perllib path is empty in the config.

**Comment by iliajie** [comment] 2022-12-07 17:24
> Changing it to LIBROOT in file-manager-lib.pl fixes the errors.

You can grab the latest `.tar.gz` package that includes this fix from here:

https://builds.webmin.dev/

It all must be fixed!

**Comment by lionslair** [comment] 2022-12-08 23:55
so will the issue be fixed in the next release?

**Comment by iliajie** [comment] 2022-12-09 20:08
Yes, I expect all issues in Webmin 2.010 are fixed now.

**Closed** 2023-09-28 18:06 UTC

**Comment by agattorno** [comment] 2024-05-09 17:05
I upgrade to webmin-2.111 and have the same bug.
Error — Perl execution failed

Undefined subroutine &main::authentic called at /usr/share/webmin-2.111/authentic-theme/index.cgi line 12.

**Comment by iliajie** [comment] 2024-05-09 17:18
How did you install your Webmin in the first place? How did you upgrade your Webmin the last time?

Did you try restarting Webmin manually?

**Comment by agattorno** [comment] 2024-05-09 17:57
> How did you install your Webmin in the first place? How did you upgrade your Webmin the last time?
> 
> Did you try restarting Webmin manually?

Sorry for not explain me correctly:
i try to upgrade the webmin instalation present in a debian 11 Proxmox container from Turnkey proyects.
this container full updated has these versions:
Webmin version | 2.001
Authentic theme version | 20.01.1:5

**miniserv.error**
```
[09/May/2024:14:53:45 -0300] [127.0.0.1] /stats.cgi : Perl execution failed : Can't locate Async.pm in @INC (you may need to install the Async module) (@INC contains: /usr/share/webmin-2.111/vendor_perl /usr/share/webmin-2.111 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl /usr/share/webmin-2.111/ .) at /usr/share/webmin-2.111/authentic-theme/stats.cgi line 12.
BEGIN failed--compilation aborted at /usr/share/webmin-2.111/authentic-theme/stats.cgi line 12.
```

**webmin.log**
`1715276816.8907.0 [09/May/2024 14:46:56] root 1bc28bd684ece868cc84fbf8f34b06dc 127.0.0.1 webmin upgrade.cgi "upgrade" "-" "-" mode='' version='2.111'`

**miniserv.log**
```
127.0.0.1 - root [09/May/2024:14:48:23 -0300] "GET /unauthenticated/css/bundle.min.css?201100059999999999 HTTP/1.1" 200 186958
127.0.0.1 - root [09/May/2024:14:51:09 -0300] "GET /index.cgi/?xhr-info=1 HTTP/1.1" 500 1609
```

**Comment by agattorno** [comment] 2024-05-09 18:31
seem to i need to upgrade all the server to debian 12 first

**Comment by agattorno** [comment] 2024-05-09 19:20
> > This container full updated has these versions:
> > Webmin version | 2.001
> > Authentic theme version | 20.01.1:5
> 
> Did you install Webmin as DEB package? Because it's best to install Webmin as RPM or DEB package. It makes things much easier.
> 
> You can setup Webmin repo as simple as:
> 
> ```
> wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
> sh setup-repos.sh
> ```
> 
> and then install Webmin by running:
> 
> ```
> apt-get install webmin
> ```

you save my day. i solve my problem.
1- full upgrade the VM to debian 12
2- follow your tips to re install webmin from Webmin repo with DEB package.

I was doing the update from the webmin module to upgrade

**Comment by iliajie** [comment] 2024-05-09 19:22
I'm glad it worked for you!
