### ISSUE TITLE
Cron job: Show two hour digits instead of only one ...

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1663] opened 2023-07-17 22:45 UTC
In the cron job i have a column called `Run at times` that will show when the next run will be.

In Sweden we have 24H and when we write the time we always use two hour digits even if the hour is between 0 and 9.

So if you can see here it will only show one digit as it was 12H:
![image](https://github.com/webmin/authentic-theme/assets/5789283/69f904c9-fc5c-48c8-ab69-75313a8a636e)

Is it possible to make it show 04:00, 03:10 and so on?

**Comment by jcameron** [comment] 2023-07-18 01:51
Sure, we'll do this in the next release...

**Comment by Sopor** [comment] 2023-07-21 12:13
If i open the cron job it do look like this:
![image](https://github.com/webmin/authentic-theme/assets/5789283/70d26e92-5ef7-4a9f-895d-d4f663da7b9a)

Why does it show two hour digits here and AM? How do i change it to show 24H?

**Comment by iliajie** [comment] 2023-07-21 12:44
> Why does it show two hour digits here and AM? How do i change it to show 24H?

You can change it here:

<img width="1438" alt="image" src="https://github.com/webmin/authentic-theme/assets/4426533/9d39b599-8d4d-4cef-916a-68d441f517cb">

**Comment by Sopor** [comment] 2023-07-21 20:55
As you can see above it use mm/dd/yy but this is what i have selected:
![image](https://github.com/webmin/authentic-theme/assets/5789283/77c0f9b6-423d-4103-9668-19cff64098d7)

I use global dates format.

**Comment by iliajie** [comment] 2023-07-21 20:58
You should install `deb` or `rpm` package to install [dependencies](https://github.com/webmin/webmin/blob/master/makerpm.pl#L90), rather than installing Webmin manually.

**Comment by Sopor** [comment] 2023-07-21 20:59
I will only point out that if i change something in the `Change Language and Theme` and i leave without clicking on `Make changes` it will not tell me that i have made any changes to the page.

**Comment by Sopor** [comment] 2023-07-21 21:05
> You should install `deb` or `rpm` package to install [dependencies](https://github.com/webmin/webmin/blob/master/makerpm.pl#L90), rather than installing Webmin manually.

I have always follow the instructions and that is to add `jcameron-key.asc` and install it.

**Comment by iliajie** [comment] 2023-07-21 21:06
> I have always follow the instructions and that is to add `jcameron-key.asc` and install it.

Please check these instructions: https://webmin.com/download/

**Comment by Sopor** [comment] 2023-07-21 21:07
> Please check these instructions: https://webmin.com/download/

That is something i never have seen. Must be something new ...

**Comment by iliajie** [comment] 2023-07-21 21:09
OS?

**Comment by Sopor** [comment] 2023-07-21 21:25
Debian Linux 11 (DietPi) and Ubuntu Linux 22.04.2.

That Webmin page did not looked like that the last time i was there, but it was a couple of years ago.
This is how it looked:
https://web.archive.org/web/20230105071228/https://www.webmin.com
And those news are from November last year, so the site must have been changed a lot.

This is how i install Webmin:
https://www.digitalocean.com/community/tutorials/how-to-install-webmin-on-ubuntu-20-04

**Comment by iliajie** [comment] 2023-07-21 21:25
Try installing locale-related Perl dependencies:

```
apt-get install libdatetime-perl libdatetime-timezone-perl libdatetime-locale-perl libtime-piece-perl
```

**Comment by Sopor** [comment] 2023-07-24 16:10
All the above Perl dependencies was already installed.

**Comment by Sopor** [comment] 2023-07-24 16:40
I have now updated to Webmin 2.100 and it seems that you have removed the date format from `Change Language and Theme` and replaced it with `Locale`.

It seems that the hour now have two digits, but it will still show 12H and not 24H even after i changed Locale to Swedish.

The Language i use is still English.

![image](https://github.com/webmin/authentic-theme/assets/5789283/91674dc8-e719-4df4-8ec2-8b8b2bddb031)

**Comment by iliajie** [comment] 2023-07-24 20:08
> It seems that the hour now have two digits, but it will still show 12H and not 24H even after i changed Locale to Swedish.

Well, now I see the bug that's causing it. You can update theme to the latest development version from theme configuration page to have it fixed. Give it a try.

**Comment by Sopor** [comment] 2023-07-29 22:23
I'm now running AT 21.02, but i still get 12H.

I tried to cleared the cache too, but no luck 😥

**Comment by iliajie** [comment] 2023-07-29 22:54
> I'm now running AT 21.02, but i still get 12H.

I'm pretty sure it should work! Try incognito tab to make sure that cache isn't in the way.

Also, make sure that you set the correct locale for the user. If it doesn't work, provide screenshots for locale select and the dashboard ..

**Comment by Sopor** [comment] 2023-07-30 16:22
![image](https://github.com/webmin/authentic-theme/assets/5789283/a0e83885-f96e-4fc9-b564-7f8022fe31c9)

![image](https://github.com/webmin/authentic-theme/assets/5789283/eb70afe8-4f00-4246-811d-3602da65a621)

![image](https://github.com/webmin/authentic-theme/assets/5789283/ea3c4713-478c-4a03-8edf-1fd9aef8d31f)

After changing Global locale to Swedish, it is working, but i did that in the Webmin language and locale
![image](https://github.com/webmin/authentic-theme/assets/5789283/55a09a0c-0133-467c-9314-de80588159d2)

And now it look like this in `Change language and locale` and I still have `Personal choice` enabled
![image](https://github.com/webmin/authentic-theme/assets/5789283/04b2a952-a478-4159-be43-849b9f353310)

You can see below it is working now, but something isn't right because it will only work when i change Global locale language
![image](https://github.com/webmin/authentic-theme/assets/5789283/903bc8cb-5ae7-4730-b76e-da7be1586550)

**Comment by iliajie** [comment] 2023-07-31 00:22
> You can see below it is working now, but something isn't right because it will only work when i change Global locale language

I'm pretty sure it also works with local locale settings too! At least it works for me in all tests.

**Comment by Sopor** [comment] 2023-07-31 17:40
I did have some custom date/time before that you helped me to add, but it seems that you have removed it or should i say, i can't find it. 

Could that be the reason it is not working now?

**Comment by iliajie** [comment] 2023-07-31 17:44
Could you remind me what was that exactly?

**Comment by Sopor** [comment] 2023-07-31 22:11
It must have been #667

**Comment by iliajie** [comment] 2023-08-01 00:22
> It must have been #667

Yeah, changing format for dates may have an effect.

Try running in the browser's console:

```
config_portable_theme_locale_format_full = 'LLLL';
config_portable_theme_locale_format_long = 'LL';
config_portable_theme_locale_format_short = 'L';
config_portable_theme_locale_format_time = 'LT';
theme.config.save();
```

**Comment by Sopor** [comment] 2023-08-01 12:09
Now it got even worse.

Now it has changed to 12H or the dashboard too:
![image](https://github.com/webmin/authentic-theme/assets/5789283/c4a921bd-4ce5-4892-8c5b-4603df04eedb)

I even tried to change it to `Global locale` and back again to Swedish, but it was still 12H.

I have cleared the cache and tried Private window, but it doesn't help. 😥

**Comment by iliajie** [comment] 2023-08-01 12:10
> I have cleared the cache and tried Private window, but it doesn't help. 😥

Is there a way I could remotely login to that system and have a look?

**Comment by iliajie** [comment] 2023-08-01 12:11
By the way, the latest theme version is 21.03.

**Comment by Sopor** [comment] 2023-08-01 12:24
No difference after update to 21.03

**Comment by Sopor** [comment] 2023-08-01 12:34
I have three Webmin's and one of them don't have locale to choose from. Only date format.

Do you know why?

It is the same version of Webmin and AT as the other two:
![image](https://github.com/webmin/authentic-theme/assets/5789283/d11ef232-e0fa-4721-b453-e41029b9f546)

**Comment by iliajie** [comment] 2023-08-01 12:35
> Do you know why?

You need to install dependencies:

```
apt-get install libdatetime-perl libdatetime-timezone-perl libdatetime-locale-perl libtime-piece-perl
```

**Comment by Sopor** [comment] 2023-08-01 12:38
```
0 upgraded, 37 newly installed, 0 to remove and 6 not upgraded.
Need to get 3,767 kB of archives.
After this operation, 28.6 MB of additional disk space will be used.
```

It seems that there was a lot of them missing 😁

**Comment by Sopor** [comment] 2023-08-01 12:44
I wanted to see if all three Webmin's have the same behaviours and they do. They all show 12H when changing to Locale Sverige when i select that in the Personal choice. It will only work if i change the Global locale.

**Comment by Sopor** [comment] 2023-08-01 13:15
No, it is not working. I need to change the Global locale for it to work.

Why did you add Personal choice when it is not working?

**Comment by iliajie** [comment] 2023-08-01 13:17
> Why did you add Personal choice when it is not working?

~Sadly~ it works for me on all systems I tried/tested.

If you open browser console and run `session.server.data('locale')` .. what output do you get?

**Comment by Sopor** [comment] 2023-08-01 13:18
```
15:18:07.873 session.server.data('locale')
15:18:07.897 "sv-SE"
```

**Comment by iliajie** [comment] 2023-08-01 13:21
> 15:18:07.897 "sv-SE"

That just _has_ to work then! I really don't know why it's not working for you .. Sorry .. Does this happen for you on all systems you tried? Is this Debian 11?

**Comment by Sopor** [comment] 2023-08-01 13:21
If i change Global locale to English, but keep Personal choice to Sverige i get this:
```
15:19:56.028 session.server.data('locale')
15:19:56.047 "en" 
```

**Comment by Sopor** [comment] 2023-08-01 13:23
Two are running Debian 11 and one is running Ubuntu Linux 22.04.2.

**Comment by iliajie** [comment] 2023-08-01 13:32
Can you show the screenshot of configuration page, e.g. this is what I get with global set to English and local to Swedish:

<img width="1440" alt="image" src="https://github.com/webmin/authentic-theme/assets/4426533/a2b8cb9a-0656-41f3-a92e-ec0ca00c4132">

What

**Comment by Sopor** [comment] 2023-08-01 14:26
![image](https://github.com/webmin/authentic-theme/assets/5789283/afd956a1-726d-4176-ac06-93937dda7cc1)

**Comment by Sopor** [comment] 2023-08-01 14:31
I'm running Firefox 105.0.2 on Windows 10 22H2 x64, but i did a test in Chrome and it was no difference. 🙁

**Comment by iliajie** [comment] 2023-08-02 21:41
Yet, it still works for me immaculately! I really don't understand what's happening on your side.

What is the out put of the following command on your system?

```
grep locale /etc/webmin/config
```

**Comment by Sopor** [comment] 2023-08-02 23:35
```
$ grep locale /etc/webmin/config
locale=en
locale_root=sv-SE
```

**Comment by Sopor** [comment] 2023-08-03 20:20
![image](https://github.com/webmin/authentic-theme/assets/5789283/f5614f4c-cfac-4552-bdd2-dac39041030d)

**Comment by iliajie** [comment] 2023-08-03 20:26
I'm sorry that I cannot help you with solving this issue! I don't know what's wrong. It simply works for me on literally all ten different machines I have tried.

Send me via email your `/etc/webmin` config directory. I will try to reproduce this issue using all your configs.

**Comment by Sopor** [comment] 2023-08-03 21:23
Are you logged in as root or with a user that has sudo privileges?

**Comment by iliajie** [comment] 2023-08-03 21:44
Alright, now I see the bug!

Discussion related to this issue is also here https://github.com/webmin/webmin/commit/407ce7ea10735e9f2947ba7985c3bd68d5067798.

**Comment by iliajie** [comment] 2023-08-04 10:02
@Sopor This bug was fixed in the latest Webmin nightly version.

Although, @jcameron I'm surprised that root-capable user cannot have its own specific **theme**, **language** and **locale** set. It doesn't seem right. I'm not sure why this is like this, as it doesn't seem hard to implement. I was going to do it now but decided that it would be better to postpone it. Should I add this to my todo to the next Webmin release (after 2.101)?

**Closed by iliajie** 2023-08-04 10:02 UTC
