### ISSUE TITLE
No support for 24 hour format.

### ISSUE THREAD

**Issue by Draywen** [webmin/authentic-theme#1676] opened 2023-09-22 21:49 UTC
There doesn't seem to be an option to change the date to 24 hour format in dashboard. There is only the option to change the date format.
24 hour format works in other themes.
System time and time in the terminal show 24 hour format.
This needs to be fixed.

**Comment by iliajie** [comment] 2023-09-23 19:00
Hello,

You can change locale on this page:

<img width="1107" alt="image" src="https://github.com/webmin/authentic-theme/assets/4426533/80c56d99-e247-4df8-8874-ef91bb41b81b">

**Comment by Draywen** [comment] 2023-09-24 02:46
First, I want to keep English as the language but choose to show 24 hour format.
Secondly, even if I change the location to something else (in my case swedish), the time is still shown as AM/PM.
As said, this works fine in other themes such as Framed theme.

**Comment by iliajie** [comment] 2023-09-24 08:12
> As said, this works fine in other themes such as Framed theme.

Where exactly you have it shown incorrectly? Can you show a screenshot?

**Comment by Draywen** [comment] 2023-09-24 11:43
![Screenshot (228)](https://github.com/webmin/authentic-theme/assets/89684837/bcd27b17-7dc8-48e8-95dd-4dfd340cbc53)

**Comment by Draywen** [comment] 2023-09-24 11:55
![Framed theme time](https://github.com/webmin/authentic-theme/assets/89684837/75465157-d8b4-4193-b930-28b31a245a16)

Other theme shows the 24 hours format.

**Comment by iliajie** [comment] 2023-09-24 13:15
If you set it to **English (Swedish)** it should display time correctly (after a full page reload) for you, i.e.:

<img width="1147" alt="image" src="https://github.com/webmin/authentic-theme/assets/4426533/75353a69-7211-4aa2-8a8b-4fa5424ac2cc">

Although, in this case you may have month and day displayed in Swedish language. As the UI dates parsed with the day.js library, I don't think there is much I can do to fix it. You can suggest `en-sv` to [day.js](https://github.com/iamkun/dayjs/tree/dev/src/locale) repo though.

Nevertheless, I'm pretty sure it won't be a problem for you to set it to **English (United Kingdom)** to have it displayed as you wish (in English and without a.m./p.m.).

**Comment by Draywen** [comment] 2023-09-24 13:45
I now see that I can only change the language and not locale. It is completely missing in my webmin.

![Language and locale](https://github.com/webmin/authentic-theme/assets/89684837/dec939a3-e47a-42d3-8028-4cb0e5f8f76b)

![Languange and theme](https://github.com/webmin/authentic-theme/assets/89684837/5cac62c4-25e4-43b5-86be-c04e3dc2121e)

**Comment by iliajie** [comment] 2023-09-24 13:48
> It is completely missing in my webmin.

```
apt-get install libdatetime-perl libdatetime-timezone-perl libdatetime-locale-perl libtime-piece-perl
```

**Comment by Draywen** [comment] 2023-09-24 14:54
Ok I have followed your instructions and now I have locale installed in the system.

Unfortunately when I choose **English (Swedish)** the language for date and time is neither English nor Swedish 🙂
It shows date and time in northern sami finnish language.
I don't know why

![Swedish locale but wrong language](https://github.com/webmin/authentic-theme/assets/89684837/73ddc651-8443-4ce6-a41f-0d39381d0fda)


--------------------------------------------------------
I had to do a workaround with the problem by selecting **English (United Kingdom)** as you also mentioned
![English UK locale - 24 hour format](https://github.com/webmin/authentic-theme/assets/89684837/fe1f8794-b299-4286-9bb3-3257376c66eb)

**Comment by iliajie** [comment] 2023-09-26 12:41
I see now. The problem is that we didn't distinguish correctly between `en-SV` and `en-SE`. It will be fixed in the next Webmin release.

Thanks for the heads up!

> I had to do a workaround with the problem by selecting English (United Kingdom) as you also mentioned

Yeah, I think it would work. However, my personal favorite would be the US locale with 24 hour format. I will look into implementing it.

**Comment by iliajie** [comment] 2023-09-26 16:28
Alright, next Webmin release will have a new `English (United States) (military time)` locale with 24 hour format support.

**Closed by iliajie** 2023-09-26 16:28 UTC

**Comment by Draywen** [comment] 2023-09-26 18:42
Thanks a lot!
